### ISSUE TITLE
1.16.5 ToDo list

### ISSUE THREAD

**Issue by InfinityRaider** [AgriCraft/AgriCraft#1298]
Things to implement / finish / polish before release:
  * [x] Implement the Agricultural Journal
  * [x] Implement the Magnifying Glass
  * [x] Implement the Seed Bag
  * [x] Fix the Tag (former OreDict) plant drops
  * [x] Fix the Irrigation Systems
  * [x] Add new jsons for new Vanilla crops
  * [x] Add clipper drops to Flower crops
  * [x] Specify humidity, acidity and nutrients for vanilla soils
  * [x] Define humidity, acidity and nutrients requirements for vanilla and resource crops
  * [ ] Add jsons for crops, soils and mutations for other mods (see #1292)
  * [x] Add animal crop eating behaviours
  * [x] Add JEI support for the Custom Wood Recipes (InfinityLib)
  * [x] Add JEI support for the soils
  * [x] Add JEI support for soil requirements
  * [x] Add JEI support for the Clipper
  * [ ] Add (non json) cross-mod compatibility (see #1297)
  * [x] Clear AgriPlants [issue tracker](https://github.com/AgriCraft/AgriPlants/issues)
  * [x] Fix existing bugs (see #1302)
  * [ ] Write documentation for the jsons
